/*
 * This source file was generated by the Gradle 'init' task
 */
package eu.nourishedminds

import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.TaskAction

/**
 * A simple 'hello world' plugin.
 */
class LicensePlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("license", LicenseTask) { task ->
            task.setDescription("add a license header to the source code")
            task.setGroup("from license plugin")
        }
    }
}

abstract class LicenseTask extends DefaultTask {

    @Input
    def fileName = project.rootDir.toString() + "/LICENSE.txt"

    @TaskAction
    void action(){
        def licenseText = new File(fileName).text
        new File(project.rootDir.toString()).eachFileRecurse { file ->
            int lastIndexOf = file.getName().lastIndexOf(".")
            if((lastIndexOf != -1) && (file.getName().substring(lastIndexOf)) == ".java"){
                def content = file.getText()
                file.text = licenseText + "\n" + content
            }
        }

    }

}